#!/usr/bin/env python3
"""lora_finetune.py — prepare (and, if tooling is present, launch) a LoRA fine-tune (#4 scaffold).

This script does NOT implement a training loop and will NEVER fabricate a trained adapter. LoRA
training needs a CUDA training stack (unsloth / llama-factory / axolotl) that is intentionally NOT
a dependency of this lightweight forecasting pipeline. What this script DOES:

  1. Ensure the SFT dataset exists (build it via build_lora_dataset.py if missing).
  2. Gate on corpus size — refuse to even emit a launch command when the usable record is too small
     to fine-tune without overfitting (the manifest's below_min_n flag).
  3. Detect whether a training backend is importable on THIS machine (the home RTX GPU box).
  4. Emit a ready-to-run training config + an Ollama Modelfile for re-importing the merged weights,
     and print the exact commands. If a backend is present and --launch is passed, run it; otherwise
     print the recipe and stop (honest about what actually happened).

Usage:
  python3 scripts/lora_finetune.py                 # prepare configs + print recipe (default; no training)
  python3 scripts/lora_finetune.py --launch        # additionally run llama-factory IF it is installed
  python3 scripts/lora_finetune.py --base mistral  # target the Mistral arm instead of Qwen
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from lib import config  # noqa: E402

LORA_DIR = config.DATA_DIR / "lora"


def _backend_available() -> str | None:
    for mod, name in (("llamafactory", "llama-factory"), ("unsloth", "unsloth"),
                      ("axolotl", "axolotl")):
        if importlib.util.find_spec(mod) is not None:
            return name
    return None


def _ensure_dataset() -> dict:
    manifest_path = LORA_DIR / "manifest.json"
    if not manifest_path.exists():
        print("dataset missing — building it now via build_lora_dataset.py ...")
        subprocess.run([sys.executable, "scripts/build_lora_dataset.py"], check=True)
    return json.loads(manifest_path.read_text())


def _write_llamafactory_config(base_tag: str, base_repo: str) -> Path:
    """Emit a llama-factory training YAML targeting the local SFT files. base_repo is the HF id of
    the base weights (Ollama tags are quantized GGUFs; LoRA trains on the HF safetensors base, then
    you re-quantize for Ollama — see docs/LORA.md)."""
    cfg = f"""\
### llama-factory LoRA SFT — auto-generated by scripts/lora_finetune.py
### base: {base_tag} (HF: {base_repo}); trains on the resolved-record SFT export.
model_name_or_path: {base_repo}
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05

dataset_dir: {LORA_DIR}
dataset: kalshi_sft           # register sft_train.jsonl in dataset_info.json (see docs/LORA.md)
template: {'qwen' if 'qwen' in base_tag else 'mistral'}
cutoff_len: 4096
overwrite_cache: true

output_dir: {LORA_DIR / (base_tag.replace(':', '_') + '_lora')}
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
logging_steps: 5
save_steps: 50
val_size: 0.0                 # we hold out sft_val.jsonl ourselves; evaluate post-hoc on it
plot_loss: true
"""
    p = LORA_DIR / f"llamafactory_{base_tag.replace(':', '_')}.yaml"
    p.write_text(cfg)
    return p


def _write_dataset_info() -> Path:
    """llama-factory needs a dataset_info.json describing the messages-format file."""
    info = {
        "kalshi_sft": {
            "file_name": "sft_train.jsonl",
            "formatting": "sharegpt",
            "columns": {"messages": "messages"},
            "tags": {"role_tag": "role", "content_tag": "content",
                     "user_tag": "user", "assistant_tag": "assistant", "system_tag": "system"},
        }
    }
    p = LORA_DIR / "dataset_info.json"
    p.write_text(json.dumps(info, indent=2))
    return p


def _write_ollama_modelfile(base_tag: str) -> Path:
    """Template for re-importing the MERGED (base+LoRA, re-quantized to GGUF) weights into Ollama so
    the forecasting pipeline can select it as a competing arm on the scoreboard."""
    name = base_tag.replace(":", "_") + "_lora"
    mf = f"""\
# Ollama Modelfile — import the merged + re-quantized GGUF as a competing forecaster arm.
# After llama-factory `export` merges the adapter and you convert to GGUF (llama.cpp
# convert + quantize), point FROM at that .gguf, then: `ollama create kalshi-{name} -f Modelfile`
FROM ./{name}.gguf
PARAMETER temperature 0.7
# Match the live forecaster's thinking-suppression so the ensemble budget is not blown.
PARAMETER num_ctx 8192
"""
    p = LORA_DIR / f"Modelfile.{name}"
    p.write_text(mf)
    return p


# HF base repos corresponding to the Ollama tags (the LoRA trains on these, not the GGUF).
_BASE_REPO = {
    "qwen": ("qwen", config.LOCAL_LLM_MODEL, "Qwen/Qwen3-14B"),
    "mistral": ("mistral", config.LOCAL_LLM_MODEL_MISTRAL, "mistralai/Mistral-Small-24B-Instruct-2501"),
}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--base", choices=["qwen", "mistral"], default="qwen")
    ap.add_argument("--launch", action="store_true",
                    help="actually run training IF a backend is importable (default: prepare only)")
    args = ap.parse_args()

    manifest = _ensure_dataset()
    _, base_tag, base_repo = _BASE_REPO[args.base]

    print(f"\nDataset: {manifest['n_examples']} examples "
          f"({manifest['n_reinforce_beat_market']} reinforce / {manifest['n_defer_to_crowd']} defer-to-crowd), "
          f"train={manifest['n_train']} val={manifest['n_val']}")

    if manifest.get("below_min_n"):
        print(f"\nREFUSING to train: only {manifest['n_examples']} usable examples "
              f"(< min_n={manifest['min_n']}). A LoRA on this few WILL overfit and degrade the "
              f"forecaster. Keep accruing resolutions; re-run when the corpus is larger.\n"
              f"(Configs are still written so the pipeline is ready.)")

    cfg_path = _write_llamafactory_config(base_tag, base_repo)
    info_path = _write_dataset_info()
    mf_path = _write_ollama_modelfile(base_tag)
    backend = _backend_available()

    print("\nWrote training configs:")
    print(f"  - {cfg_path}")
    print(f"  - {info_path}")
    print(f"  - {mf_path}")
    print(f"\nTraining backend on this machine: {backend or 'NONE detected'}")

    can_train = backend == "llama-factory" and not manifest.get("below_min_n")
    if args.launch and can_train:
        print("\nLaunching llama-factory LoRA SFT ...")
        rc = subprocess.run(["llamafactory-cli", "train", str(cfg_path)]).returncode
        print(f"llama-factory exited {rc}.")
        return rc

    # Honest path: we did not train. Print the exact recipe.
    print(f"""
NOT TRAINED (this script never fabricates an adapter). To run on the home GPU:

  1. Install a backend (one-time):    pip install llama-factory   # or: pip install unsloth
  2. Train the adapter:               llamafactory-cli train {cfg_path}
  3. Merge adapter into base:         llamafactory-cli export ... (merge_lora)  # see docs/LORA.md
  4. Convert+quantize to GGUF:        llama.cpp convert_hf_to_gguf.py + quantize  # docs/LORA.md
  5. Import into Ollama:              ollama create kalshi-{base_tag.replace(':','_')}_lora -f {mf_path}
  6. Register as a competing arm:     add the new Ollama tag to lib/strategies (a new LQ*-lora arm)
     and let the bandit + shadow A/B measure it against the stock model on REAL resolutions.

The fine-tune only earns its place if it BEATS the stock model on the held-out record — the
scoreboard decides, exactly like the Mistral arm. See docs/LORA.md for the full pipeline.
""")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
